name: Notifier

on: [pull_request, issues]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: NotifyOpsGenie
        run: |
              cat << EOF > contents.json
              {
                  "message": "${GITHUB_EVENT_NAME} raised against ${GITHUB_REPOSITORY}",
                  "alias": "${GITHUB_REPOSITORY} requires attention",
                  "description": "${GITHUB_EVENT_NAME} raised against ${GITHUB_REPOSITORY}",
                  "details":{"key1":"value1","key2":"value2"},
                  "priority":"P2"
              }
              EOF

              curl -X POST https://api.opsgenie.com/v2/alerts \
                  -H "Content-Type: application/json" \
                  -H "Authorization: GenieKey ${{ secrets.OPSGENIE }}" \
                  -d "@contents.json"

